/**
 * Standalone API client - replaces @base44/sdk
  * 
   * This client provides a simple interface for data operations.
    * Connect this to your own backend (Supabase, Firebase, REST API, etc.)
     * by replacing the methods below with real API calls.
      */

      // Simple in-memory store for local development
      // Replace with real API calls to your backend
      const createLocalEntity = (entityName) => {
        const storageKey = `itimeyou_${entityName}`;

          const getAll = () => {
              try {
                    return JSON.parse(localStorage.getItem(storageKey) || '[]');
                        } catch {
                              return [];
                                  }
                                    };

                                      const save = (items) => {
                                          localStorage.setItem(storageKey, JSON.stringify(items));
                                            };

                                              return {
                                                  list: async (filters = {}) => {
                                                        let items = getAll();
                                                              // Simple filter support
                                                                    Object.entries(filters).forEach(([key, value]) => {
                                                                            if (value !== undefined && value !== null) {
                                                                                      items = items.filter(item => item[key] === value);
                                                                                              }
                                                                                                    });
                                                                                                          return items;
                                                                                                              },
                                                                                                              
                                                                                                                  get: async (id) => {
                                                                                                                        const items = getAll();
                                                                                                                              return items.find(item => item.id === id) || null;
                                                                                                                                  },
                                                                                                                                  
                                                                                                                                      create: async (data) => {
                                                                                                                                            const items = getAll();
                                                                                                                                                  const newItem = {
                                                                                                                                                          ...data,
                                                                                                                                                                  id: crypto.randomUUID(),
                                                                                                                                                                          created_date: new Date().toISOString(),
                                                                                                                                                                                  updated_date: new Date().toISOString(),
                                                                                                                                                                                        };
                                                                                                                                                                                              items.push(newItem);
                                                                                                                                                                                                    save(items);
                                                                                                                                                                                                          return newItem;
                                                                                                                                                                                                              },
                                                                                                                                                                                                              
                                                                                                                                                                                                                  update: async (id, data) => {
                                                                                                                                                                                                                        const items = getAll();
                                                                                                                                                                                                                              const index = items.findIndex(item => item.id === id);
                                                                                                                                                                                                                                    if (index === -1) throw new Error(`${entityName} not found: ${id}`);
                                                                                                                                                                                                                                          items[index] = { ...items[index], ...data, updated_date: new Date().toISOString() };
                                                                                                                                                                                                                                                save(items);
                                                                                                                                                                                                                                                      return items[index];
                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                              delete: async (id) => {
                                                                                                                                                                                                                                                                    const items = getAll();
                                                                                                                                                                                                                                                                          const filtered = items.filter(item => item.id !== id);
                                                                                                                                                                                                                                                                                save(filtered);
                                                                                                                                                                                                                                                                                      return { success: true };
                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                            // Auth module - replace with real authentication (Supabase, Firebase, Clerk, etc.)
                                                                                                                                                                                                                                                                                            const auth = {
                                                                                                                                                                                                                                                                                              me: async () => {
                                                                                                                                                                                                                                                                                                  const user = localStorage.getItem('itimeyou_user');
                                                                                                                                                                                                                                                                                                      if (!user) throw { status: 401, message: 'Not authenticated' };
                                                                                                                                                                                                                                                                                                          return JSON.parse(user);
                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                              login: async (email, password) => {
                                                                                                                                                                                                                                                                                                                  // TODO: Replace with real auth call
                                                                                                                                                                                                                                                                                                                      const mockUser = { id: '1', email, full_name: email.split('@')[0] };
                                                                                                                                                                                                                                                                                                                          localStorage.setItem('itimeyou_user', JSON.stringify(mockUser));
                                                                                                                                                                                                                                                                                                                              return mockUser;
                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                  logout: (redirectUrl) => {
                                                                                                                                                                                                                                                                                                                                      localStorage.removeItem('itimeyou_user');
                                                                                                                                                                                                                                                                                                                                          if (redirectUrl) {
                                                                                                                                                                                                                                                                                                                                                window.location.href = redirectUrl;
                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                        redirectToLogin: (returnUrl) => {
                                                                                                                                                                                                                                                                                                                                                            // TODO: Replace with your login route
                                                                                                                                                                                                                                                                                                                                                                window.location.href = `/login?return=${encodeURIComponent(returnUrl || window.location.href)}`;
                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                  // Export the client object
                                                                                                                                                                                                                                                                                                                                                                  export const base44 = {
                                                                                                                                                                                                                                                                                                                                                                    auth,
                                                                                                                                                                                                                                                                                                                                                                      entities: {
                                                                                                                                                                                                                                                                                                                                                                          Booking: createLocalEntity('Booking'),
                                                                                                                                                                                                                                                                                                                                                                              Comment: createLocalEntity('Comment'),
                                                                                                                                                                                                                                                                                                                                                                                  Conversation: createLocalEntity('Conversation'),
                                                                                                                                                                                                                                                                                                                                                                                      ExchangeRateSettings: createLocalEntity('ExchangeRateSettings'),
                                                                                                                                                                                                                                                                                                                                                                                          Listing: createLocalEntity('Listing'),
                                                                                                                                                                                                                                                                                                                                                                                              Message: createLocalEntity('Message'),
                                                                                                                                                                                                                                                                                                                                                                                                  Notification: createLocalEntity('Notification'),
                                                                                                                                                                                                                                                                                                                                                                                                      PasswordReset: createLocalEntity('PasswordReset'),
                                                                                                                                                                                                                                                                                                                                                                                                          Post: createLocalEntity('Post'),
                                                                                                                                                                                                                                                                                                                                                                                                              Review: createLocalEntity('Review'),
                                                                                                                                                                                                                                                                                                                                                                                                                  ServiceBooking: createLocalEntity('ServiceBooking'),
                                                                                                                                                                                                                                                                                                                                                                                                                      UserProfile: createLocalEntity('UserProfile'),
                                                                                                                                                                                                                                                                                                                                                                                                                          WalletAccountSettings: createLocalEntity('WalletAccountSettings'),
                                                                                                                                                                                                                                                                                                                                                                                                                              WalletTransaction: createLocalEntity('WalletTransaction'),
                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                  integrations: {},
                                                                                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                  export default base44;
